# Generated by Django 3.1.3 on 2020-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_uploaddados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddados',
            name='arquivo',
            field=models.FileField(help_text='Envie o arquivo no formato especificado neste <a href="https://drive.google.com/file/d/1Y_yQAKVMWj5e42_Bawun3-y1nsyIJ-oD/view?usp=sharing" target="_blank">link</a>. Não altere os campos, nem adicione estilização ao documento!', upload_to='uploads/%Y/', verbose_name='Arquivo CSV'),
        ),
    ]
